# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "if (!'covr' %in% rownames(installed.packages())) install.packages('covr')"
  - Rscript -e "if (!'rgl' %in% rownames(installed.packages())) install.packages('rgl')"
  - Rscript -e "if (!'roxygen2' %in% rownames(installed.packages())) install.packages('roxygen2')"
  # Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

after_success:
  - Rscript -e 'covr::codecov()'